// This file will be auto-generated by: pnpm db:generate-types
// For now, define the types manually to match our migrations.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          role: 'owner' | 'manager' | 'supervisor' | 'staff';
          phone: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name: string;
          role?: 'owner' | 'manager' | 'supervisor' | 'staff';
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string;
          role?: 'owner' | 'manager' | 'supervisor' | 'staff';
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          target_margin: number | null;
          parent_id: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          target_margin?: number | null;
          parent_id?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          name?: string;
          target_margin?: number | null;
          parent_id?: string | null;
          sort_order?: number;
        };
      };
      suppliers: {
        Row: {
          id: string;
          name: string;
          contact_phone: string | null;
          contact_email: string | null;
          delivery_days: string | null;
          lead_time_days: number | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          contact_phone?: string | null;
          contact_email?: string | null;
          delivery_days?: string | null;
          lead_time_days?: number | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          name?: string;
          contact_phone?: string | null;
          contact_email?: string | null;
          delivery_days?: string | null;
          lead_time_days?: number | null;
          notes?: string | null;
          is_active?: boolean;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          barcode: string | null;
          category_id: string | null;
          subcategory_id: string | null;
          cost_price: number | null;
          selling_price: number;
          target_margin: number | null;
          supplier_id: string | null;
          reorder_point: number | null;
          reorder_qty: number | null;
          shelf_location: string | null;
          unit_of_measure: string;
          is_active: boolean;
          is_produce: boolean;
          is_weight_based: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          barcode?: string | null;
          category_id?: string | null;
          subcategory_id?: string | null;
          cost_price?: number | null;
          selling_price: number;
          target_margin?: number | null;
          supplier_id?: string | null;
          reorder_point?: number | null;
          reorder_qty?: number | null;
          shelf_location?: string | null;
          unit_of_measure?: string;
          is_active?: boolean;
          is_produce?: boolean;
          is_weight_based?: boolean;
        };
        Update: {
          name?: string;
          barcode?: string | null;
          category_id?: string | null;
          subcategory_id?: string | null;
          cost_price?: number | null;
          selling_price?: number;
          target_margin?: number | null;
          supplier_id?: string | null;
          reorder_point?: number | null;
          reorder_qty?: number | null;
          shelf_location?: string | null;
          unit_of_measure?: string;
          is_active?: boolean;
          is_produce?: boolean;
          is_weight_based?: boolean;
        };
      };
      daily_prices: {
        Row: {
          id: string;
          product_id: string;
          cost_price: number | null;
          selling_price: number;
          effective_date: string;
          set_by_user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          cost_price?: number | null;
          selling_price: number;
          effective_date: string;
          set_by_user_id: string;
          created_at?: string;
        };
        Update: {
          cost_price?: number | null;
          selling_price?: number;
          effective_date?: string;
        };
      };
      stock_events: {
        Row: {
          id: string;
          product_id: string;
          event_type: 'stockout' | 'restock_request' | 'delivery' | 'count' | 'expiry_flag';
          quantity: number | null;
          notes: string | null;
          photo_url: string | null;
          reported_by_user_id: string;
          resolved_by_user_id: string | null;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          event_type: 'stockout' | 'restock_request' | 'delivery' | 'count' | 'expiry_flag';
          quantity?: number | null;
          notes?: string | null;
          photo_url?: string | null;
          reported_by_user_id: string;
          resolved_by_user_id?: string | null;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: {
          quantity?: number | null;
          notes?: string | null;
          photo_url?: string | null;
          resolved_by_user_id?: string | null;
          resolved_at?: string | null;
        };
      };
      checklists: {
        Row: {
          id: string;
          checklist_type: 'opening' | 'closing';
          shift_date: string;
          completed_by_user_id: string;
          started_at: string;
          completed_at: string | null;
          status: 'in_progress' | 'completed' | 'incomplete';
          created_at: string;
        };
        Insert: {
          id?: string;
          checklist_type: 'opening' | 'closing';
          shift_date: string;
          completed_by_user_id: string;
          started_at?: string;
          completed_at?: string | null;
          status?: 'in_progress' | 'completed' | 'incomplete';
          created_at?: string;
        };
        Update: {
          completed_at?: string | null;
          status?: 'in_progress' | 'completed' | 'incomplete';
        };
      };
      checklist_items: {
        Row: {
          id: string;
          checklist_id: string;
          task_text: string;
          sort_order: number;
          is_completed: boolean;
          completed_at: string | null;
          value_entered: string | null;
          is_critical: boolean;
          escalation_sent: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          checklist_id: string;
          task_text: string;
          sort_order?: number;
          is_completed?: boolean;
          completed_at?: string | null;
          value_entered?: string | null;
          is_critical?: boolean;
          escalation_sent?: boolean;
          created_at?: string;
        };
        Update: {
          is_completed?: boolean;
          completed_at?: string | null;
          value_entered?: string | null;
          escalation_sent?: boolean;
        };
      };
      checklist_templates: {
        Row: {
          id: string;
          checklist_type: 'opening' | 'closing';
          task_text: string;
          sort_order: number;
          item_type: 'checkbox' | 'numeric' | 'cash' | 'photo';
          is_critical: boolean;
          min_value: number | null;
          max_value: number | null;
          applicable_days: number[] | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          checklist_type: 'opening' | 'closing';
          task_text: string;
          sort_order?: number;
          item_type?: 'checkbox' | 'numeric' | 'cash' | 'photo';
          is_critical?: boolean;
          min_value?: number | null;
          max_value?: number | null;
          applicable_days?: number[] | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          task_text?: string;
          sort_order?: number;
          item_type?: 'checkbox' | 'numeric' | 'cash' | 'photo';
          is_critical?: boolean;
          min_value?: number | null;
          max_value?: number | null;
          applicable_days?: number[] | null;
          is_active?: boolean;
        };
      };
      markdowns: {
        Row: {
          id: string;
          product_id: string;
          original_price: number;
          markdown_price: number;
          reason: 'approaching_expiry' | 'damaged' | 'overstock' | 'promo' | 'manager_directed' | 'other';
          approved_by_user_id: string | null;
          created_by_user_id: string;
          effective_from: string;
          effective_until: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          original_price: number;
          markdown_price: number;
          reason: 'approaching_expiry' | 'damaged' | 'overstock' | 'promo' | 'manager_directed' | 'other';
          approved_by_user_id?: string | null;
          created_by_user_id: string;
          effective_from?: string;
          effective_until?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          markdown_price?: number;
          reason?: 'approaching_expiry' | 'damaged' | 'overstock' | 'promo' | 'manager_directed' | 'other';
          approved_by_user_id?: string | null;
          effective_until?: string | null;
          is_active?: boolean;
        };
      };
      tasks: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          category: string | null;
          assigned_by_user_id: string;
          assigned_to_user_id: string | null;
          shift_date: string;
          priority: 'low' | 'normal' | 'high';
          status: 'pending' | 'in_progress' | 'done';
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          category?: string | null;
          assigned_by_user_id: string;
          assigned_to_user_id?: string | null;
          shift_date: string;
          priority?: 'low' | 'normal' | 'high';
          status?: 'pending' | 'in_progress' | 'done';
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          category?: string | null;
          assigned_to_user_id?: string | null;
          priority?: 'low' | 'normal' | 'high';
          status?: 'pending' | 'in_progress' | 'done';
          completed_at?: string | null;
        };
      };
      issues: {
        Row: {
          id: string;
          issue_type: 'equipment' | 'supplier' | 'customer' | 'staff' | 'safety' | 'other';
          title: string;
          description: string | null;
          photo_url: string | null;
          severity: 'low' | 'medium' | 'high' | 'critical';
          reported_by_user_id: string;
          resolved_by_user_id: string | null;
          status: 'open' | 'in_progress' | 'resolved';
          resolution_notes: string | null;
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          issue_type: 'equipment' | 'supplier' | 'customer' | 'staff' | 'safety' | 'other';
          title: string;
          description?: string | null;
          photo_url?: string | null;
          severity?: 'low' | 'medium' | 'high' | 'critical';
          reported_by_user_id: string;
          resolved_by_user_id?: string | null;
          status?: 'open' | 'in_progress' | 'resolved';
          resolution_notes?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          photo_url?: string | null;
          severity?: 'low' | 'medium' | 'high' | 'critical';
          resolved_by_user_id?: string | null;
          status?: 'open' | 'in_progress' | 'resolved';
          resolution_notes?: string | null;
          resolved_at?: string | null;
        };
      };
      suggestions: {
        Row: {
          id: string;
          message: string;
          category: 'product_request' | 'improvement' | 'issue' | 'other';
          is_anonymous: boolean;
          submitted_by_user_id: string;
          status: 'new' | 'reviewed' | 'actioned' | 'dismissed';
          manager_notes: string | null;
          created_at: string;
          reviewed_at: string | null;
        };
        Insert: {
          id?: string;
          message: string;
          category?: 'product_request' | 'improvement' | 'issue' | 'other';
          is_anonymous?: boolean;
          submitted_by_user_id: string;
          status?: 'new' | 'reviewed' | 'actioned' | 'dismissed';
          manager_notes?: string | null;
          created_at?: string;
        };
        Update: {
          status?: 'new' | 'reviewed' | 'actioned' | 'dismissed';
          manager_notes?: string | null;
          reviewed_at?: string | null;
        };
      };
    };
    Functions: {
      search_products: {
        Args: { search_query: string; limit_count?: number };
        Returns: Database['public']['Tables']['products']['Row'][];
      };
      get_user_role: {
        Args: { uid: string };
        Returns: string;
      };
    };
  };
}

// Convenience types
export type Tables = Database['public']['Tables'];
export type Profile = Tables['profiles']['Row'];
export type Category = Tables['categories']['Row'];
export type Supplier = Tables['suppliers']['Row'];
export type Product = Tables['products']['Row'];
export type DailyPrice = Tables['daily_prices']['Row'];
export type StockEvent = Tables['stock_events']['Row'];
export type Checklist = Tables['checklists']['Row'];
export type ChecklistItem = Tables['checklist_items']['Row'];
export type ChecklistTemplate = Tables['checklist_templates']['Row'];
export type Markdown = Tables['markdowns']['Row'];
export type Task = Tables['tasks']['Row'];
export type Issue = Tables['issues']['Row'];
export type Suggestion = Tables['suggestions']['Row'];
